config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :projects do 
    resources :bugs do 
      resources :comments
    end
  end

  get "all_bugs",to: "bugs#all_bugs",as:"all_bugs"

  devise_for :users , except: :create
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
    validates :title , presence: true , length: { minimum:3 }
    has_many :bugs , dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_project, only: [:show, :edit, :update, :destroy]

    # method to show single project
    def show
    end
    
    # method to show all project
    def index
        @projects = Project.all
    end

    # method to redirect to create project form
    def new
        @project = Project.new
    end

    # method to create project
    def create
        @project = Project.new(project_params)
        if @project.save
            flash[:success] = 'Project Added Successfully!'
            redirect_to @project
        else
            render 'new'
        end
    end

    # method to redirect to edit page
    def edit
    end

    #method to delete project. It first finds project by id then deletes
    def destroy
        @project.destroy
        flash[:danger] = 'Project Deleted!'
        redirect_to projects_path
    end

    # method to update the project
    def update
        if @project.update(project_params)
            flash[:success] = 'Project Updated!'
            redirect_to @project
        else
            render 'edit'
        end
    end

    # method for security of input params
    private
    def project_params
        params.require(:project).permit(:title)
    end
    
    def set_project
        @project = Project.find(params[:id])
    end  


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true do |form| %>
 
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@project.errors.count, "error") %> prohibited
          this project from being saved:
        </h2>
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, :class => "form-control" %>
    </p>
   
    <p>
      <%= form.submit :class => 'btn btn-success' %>
    </p>
   
  <% end %>

app/views/projects/edit.html.erb
<h1 class="text-primary text-center mt-2 mb-2">Edit project</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', projects_path,:class=>"btn btn-secondary text-white" %>

app/views/projects/index.html.erb
<h1 class="text-center mt-2 text-primary">Listing all Projects </h1>
<div class="d-flex justify-content-end">
    <%= link_to "Add New project", new_project_path ,:class=>"btn btn-success text-white mb-2 " %>
</div>
<table class="table table-striped table-bordered text-center">
    <thead>
        <tr>
            <th>Title</th>
            <th>Bugs Count</th>
            <th>Show Bugs</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @projects.each do |project| %>
            <tr>
                <td><%= project.title %></td>
                <td><%= project.bugs.count %></td>
                <td><%= link_to "Show Bugs",project_bugs_path(project),:class=>"btn btn-success text-white" %></td>
                <td><%= link_to "Show",project_path(project),:class=>"btn btn-primary text-white" %></td>
                <td><%= link_to "Edit",edit_project_path(project),:class=>"btn btn-warning text-white" %></td>
                <% if current_user.admin? %>
                <td><%= link_to 'Delete', project_path(project),
                method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-danger text-white" %></td>
                <% end %>
            </tr>
        <% end %>
    <tbody>
</table>

app/views/projects/new.html.erb
<h1 class="text-center text-primary mt-2">New project</h1>

<%= render 'form' %>

<%= link_to "Back",projects_path , :class => "btn btn-secondary text-white" %>
</div>

app/views/projects/show.html.erb
<div class="mt-2">
<div class="card">
    <h3 class="text-primary card-header">Project Title : <%= @project.title %> </h3>
    <div class="card-body">
        <% if @project.bugs.empty? %>
                <h6 class="text-danger">No Bugs in this project.</h1>
        <% else %>
        <h6 class="text-info">Total Bugs : <%= @project.bugs.count %> </h6>
        <h4 class="text-primary">Bugs List</h4>
        <ul class="list-group">
            <% @project.bugs.each do |bug| %>
                <li class="list-group-item">
                    <%= bug.title %>
                    <span class="d-flex justify-content-end">
                    <%= link_to "Detail", project_bug_path(@project,bug) , :class=>"btn btn-primary" %> 
                    </span>
                </li>
            <% end %>
        </ul>
        <% end %>
    </div>
</div>
<div class="mt-2">
    <%= link_to 'Edit', edit_project_path(@project),:class=>"btn btn-warning text-white" %>
    <%= link_to 'Delete', project_path(@project),
                    method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-danger text-white ml-3" %>
    <%= link_to "Back",projects_path,:class=>"btn btn-secondary text-white ml-3" %>
</div>    
</div>