config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :projects do 
    resources :bugs do 
      resources :comments
    end
  end

  get "all_bugs",to: "bugs#all_bugs",as:"all_bugs"

  devise_for :users , except: :create
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project
  has_many :comments , dependent: :destroy
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
    before_action :authenticate_user!

    # method to list all bugs for a project
    def index
        @project = Project.find(params[:project_id])
    end

    # method to list all bugs for all projects
    def all_bugs
        @bugs = Bug.all
    end

    def new
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.new
    end

    # method to create bug for project
    def create
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.create(bug_params)
        flash[:success] = 'Bug added!'
        redirect_to project_bug_path(@project,@bug)
    end

    # method to show single bug
    def show
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.find(params[:id])
    end

    # method to redirect to edit page
    def edit
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.find(params[:id])
    end

    # method to update
    def update
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.find(params[:id])
        if @bug.update(bug_params)
            redirect_to(project_bugs_path)
        else
          render('edit')
        end
    end

    # method to delete bug
    def destroy
        @project = Project.find(params[:project_id])
        @bug = @project.bugs.find(params[:id])
        @bug.destroy
        flash[:danger] = 'Bug deleted!'
        redirect_to project_bugs_path(@project)
    end

    private
    def bug_params
        params.require(:bug).permit(:title,:status,:description,:assigned_to)
    end                                          
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
   
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => "form-control" %>
    </p>

    <p>
      <%= f.label :status %><br>
      <%= f.select :status, ['Pending', 'Complete'], :class => "form-control" %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => "form-control" %>
    </p>

    <p>
      <%= f.label :assigned_to %><br>
      <%= f.select :assigned_to ,options_for_select(User.all.map {|p| [ p.email, p.email ] }) %>      
    </p>

app/views/bugs/all_bugs.html.erb
<div class="mt-2">
    <h1 class="text-primary text-center">All Bugs </h1>
    <table class="table table-striped table-bordered text-center">
    <thead>
        <tr>
            <th>Bug Title</th>
            <th>Project</th>
            <th>Description</th>
            <th>Status</th>
            <th>Assigned_to</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @bugs.each do |bug| %>
            <tr>
                <td><%= bug.title %></td>
                <td><%= bug.project.title %></td>
                <td><%= bug.description %></td>
                <td><%= bug.status %></td>
                <td><%= bug.assigned_to %></td>
                <td><%= link_to "Show Detail",project_bug_path(bug.project.id,bug),:class=>"btn btn-primary text-white" %></td>
                <td><%= link_to "Edit",edit_project_bug_path(bug.project.id,bug),:class=>"btn btn-warning text-white" %></td>
                <td><%= link_to 'Delete', project_bug_path(bug.project.id,bug),
                method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-danger text-white" %></td>
            </tr>
        <% end %>
    <tbody>
    </table>
</div>

app/views/bugs/edit.html.erb
<h1 class="text-center text-primary mt-2">New Bug</h1>

<%= form_for @bug, url: project_bug_path(@bug.project.id,@bug.id) do |f| %>
    
    <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.bugs.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.bugs.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= render(:partial => 'form', :locals => {:f => f}) %>  

<%= f.submit "Edit Bug", :class=>"btn btn-success" %>
<% end %>


<%= link_to "Back",project_bugs_path , :class => "mt-1 btn btn-secondary text-white" %>

app/views/bugs/index.html.erb
<div class="mt-2">
    <h1 class="text-primary text-center">Showing Bugs of <%= @project.title %> </h1>
    <div class="d-flex justify-content-end">
        <%= link_to "Add New Bug", new_project_bug_path(@project) ,:class=>"btn btn-success text-white mb-2 " %>
        <%= link_to "Back", projects_path ,:class=>"btn btn-secondary ml-2 text-white mb-2 " %>
    </div>
    <table class="table table-striped table-bordered text-center">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Assigned_to</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @project.bugs.each do |bug| %>
            <tr>
                <td><%= bug.title %></td>
                <td><%= bug.description %></td>
                <td><%= bug.status %></td>
                <td><%= bug.assigned_to %></td>
                <td><%= link_to "Show Detail",project_bug_path(@project,bug),:class=>"btn btn-primary text-white" %></td>
                <td><%= link_to "Edit",edit_project_bug_path(@project,bug),:class=>"btn btn-warning text-white" %></td>
                <td><%= link_to 'Delete', project_bug_path(@project,bug),
                method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-danger text-white" %></td>
            </tr>
        <% end %>
    <tbody>
    </table>
</div>

app/views/bugs/new.html.erb
<h1 class="text-center text-primary mt-2">New Bug</h1>

<%= form_for @bug, url: project_bugs_path(@project.id) do |f| %>
    
    <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.bugs.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.bugs.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= render(:partial => 'form', :locals => {:f => f}) %>  

<%= f.submit "Create Bug", :class=>"btn btn-success" %>
<% end %>


<%= link_to "Back",project_bugs_path , :class => "mt-1 btn btn-secondary text-white" %>

app/views/bugs/show.html.erb
<div class="mt-2">
    <div class="card">
    <h4 class="text-primary card-header">Bug : <%= @bug.title %> </h4>
        <div class="card-body mt-2">
            <p><strong>Description : </strong> <%= @bug.description %></p>
            <p><strong>Assigned To : </strong> <%= @bug.assigned_to %></p>
            <p><strong>Status : </strong> <%= @bug.status %></p>
        </div>
        <div class="card">
            <h5 class="card-header">Comments</h5>
        </div>
    </div>
    <div class="mt-2">
        <%= link_to 'Edit', edit_project_bug_path(@bug.project.id,@bug),:class=>"btn btn-warning text-white" %>
        <%= link_to 'Delete', project_bug_path(@bug.project.id,@bug),
                        method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-danger text-white ml-3" %>
        <%= link_to "Back", :back,:class=>"btn btn-secondary text-white ml-3" %>
    </div>
</div>