config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :projects do 
    resources :bugs do 
      resources :comments
    end
  end

  get "all_bugs",to: "bugs#all_bugs",as:"all_bugs"

  devise_for :users , except: :create
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/common/_footer.html.erb
<div class="footer text-center fixed-bottom">
    By Dipesh Chaudhary
<div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary mt-2">
  <%= link_to "Bug Tracker App", root_path, :class=>"navbar-brand text-white" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item active">
        <%= link_to "Projects", projects_path, :class=>"nav-link text-white"  %>
        </li>
        <li class="nav-item">
        <%= link_to "All Bugs", all_bugs_path, :class=>"nav-link text-white"  %>
        </li>
        <li class="nav-item">
        <%= link_to "New Invitation", new_user_invitation_path, :class=>"nav-link text-white"  %>
        </li>
        <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class=>"nav-link text-white"  %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Login", new_user_session_path, :class=>"nav-link text-white"  %>
        </li>
        <% end %>
      
    </ul>
  </div>
</nav>